---
apiVersion: v1
kind: Template
labels:
  template: frontend
parameters:
- name: NAME
  description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  required: true
  value: frontend

- name: NAMESPACE
  description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  required: true
  value: frontend

- name: SERVER_PORT
  description: The port the server will run on inside the container
  displayName: Server Port
  value: '8080'

- name: HIGHSCORE_SERVICE
  description: Service host of the highscore rest service
  displayName: Highscore service
  value: ""

- name: KAFKA_SERVERS
  description: Hostnames of the Kafka servers to bootstrap
  displayName: Kafka bootstrap servers
  value: "kafka"

- name: MEMORY_LIMIT
  description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  required: true
  value: 128Mi

- name: CONTEXT_DIR
  description: Set this to the relative path to your project if it is not in the root of your repository.
  displayName: Context Directory
  value: ""

- name: APPLICATION_DOMAIN
  description: The exposed hostname that will route to the service, if left blank a value will be defaulted.
  displayName: Application Hostname
  value: ''

objects:

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
    annotations:
      description: Defines how to build the application
  spec:
    source:
      type: Binary
      contextDir: "${CONTEXT_DIR}"
    strategy:
      type: Docker
      dockerStrategy:
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"

- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    ports:
    - name: http
      port: 8080
      targetPort: 8080
    selector:
      name: "${NAME}"

- kind: Route
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    host: "${APPLICATION_DOMAIN}"
    to:
      kind: Service
      name: "${NAME}"

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  selector:
    name: "${NAME}"
  spec:
    selector:
      name: "${NAME}"
    ImagePullPolicy: Always
    replicas: 1
    strategy:
      type: "Recreate"
    template:
      metadata:
        labels:
          name: "${NAME}"
        name: "${NAME}"
      spec:
        containers:
          - name: ${NAME}
            image: "${NAME}:latest"
            env:
              - name: "SERVER_PORT"
                value: "${SERVER_PORT}"
#              - name: "ENABLE_KAFKA"
#                value: "true"
              - name: "KAFKA_HOST"
                value: "${KAFKA_HOST}"
              - name: "KAFKA_TOPIC"
                value: "${KAFKA_TOPIC}"
              - name: "ZOOKEEPER_PORT"
                value: "${ZOOKEEPER_PORT}"
            ports:
            - containerPort: 8080
            readinessProbe:
              timeoutSeconds: 3
              initialDelaySeconds: 3
              httpGet:
                path: "/healthz"
                port: 8080
            livenessProbe:
              timeoutSeconds: 3
              initialDelaySeconds: 30
              httpGet:
                path: "/healthz"
                port: 8080
            resources:
              limits:
                memory: "${MEMORY_LIMIT}"
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${NAME}
          from:
            kind: ImageStreamTag
            name: "${NAME}:latest"
