version: "2"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/opt/app-root/src
    environment:
      SERVER_PORT: "8080"
      KAFKA_SERVERS: "kafka:9092"
    ports:
     - "8080:8080"
    networks:
      - front-tier
      - back-tier

  highscore:
    build: ./highscore
    ports:
      - "9090:9090"
    environment:
      SERVER_PORT: "9090"
      KAFKA_SERVERS: "kafka:9092"
      DATASOURCE_PLATFORM: postgres
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/highscore
      DATASOURCE_USER: highscore
      DATASOURCE_PASSWORD: c-krit
    networks:
      - front-tier
      - back-tier

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - front-tier
      - back-tier

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 999
    networks:
      - front-tier
      - back-tier

  postgres:
    image: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: highscore
      POSTGRES_USER: highscore
      POSTGRES_PASSWORD: c-krit
    ports:
      - "5432:5432"
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:
